#!/usr/bin/env ruby
$LOAD_PATH.push File.expand_path("../../", __FILE__)

require 'rgreek'
  include RGreek
  
def respond(msg)
  if ARGV.length < 2
    puts msg
    exit 1
  end
  ARGV.shift
  puts yield ARGV
  exit 0
end

case ARGV[0]
when "convert"  
    respond("please input the unicode text you would like transcoded") do |args| Transcoder.convert(args.join) end
else
  puts "choose a command: convert or parse"
  exit 1
end